# Simple deployment used to deploy and manage the app contained in punitporwal07/myapp:0.1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  minReadySeconds: 10
  strategy:                                > responsible to update your deployment & scale the pods to newer version and delete older one
    type: RollingUpdate                 
    rollingUpdate:
      maxUnavailable: 1                    > optional field that specifies the maximum number of Pods that can be unavailable during the update process. value can be absolute or percentage of desired Pods
      maxSurge: 1                          > optional field that specifies the maximum number of Pods that can be created over the desired number of Pods. value can be absolute or percentage of desired Pods
  template:
    metadata:
      labels:
        app: web
    spec: 
      terminationGracePeriodSeconds: 1
      containers:                           > responsible to deploy your container. Pull from hub and deploy to your cluster
      - name: web-ctr
        image: punitporwal07/myapp:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
