# Simple Kubernetes Pod to deploy the app contained in punitporwal07/myapp:0.1
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: punitporwal07/myapp:0.1
      ports:
        - containerPort: 8000
