# Simple Kubernetes Pod to deploy the app contained in punitporwal07/myapp:0.1
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: punitporwal07/myapp:0.1
      ports:
        - containerPort: 8000
...

---
apiVersion: v1
kind: Pod
metadata:
  name: ibmmq
  namespace: mq
  labels: 
    app: mq
spec:
  containers:
    - name: mq-container
      image: "registry/middleware/ibmmq:9.1.5.0"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 1414
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
      env:
        - name: LICENSE
          value: accept
        - name: MQ_QMGR_NAME
          value: QM1
...
