# service types used is nodePort with container port 80 and image port 8000
apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 31111
    protocol: TCP
  selector:
    app: web
    
