# when running this service locally use : service types as NodePort with container port 31000 and image port 8000
apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 31000
    protocol: TCP
  selector:
    app: web
    
