# A sample service YAML file with type as NodePort with port forwarding from NP(30001) > CP(1414) & NP(30002) > CP(9443)
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-np
  labels:
    run: nodeport-my                >> imp to match with your deployment label
spec:
  type: NodePort
  selector:
    run: nodeport-my                >> imp to match with your deployment label
  ports:
    - name: qm
      protocol: TCP
      port: 1414
      targetPort: 1414
      nodePort: 30001
    - name: webserver
      protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 30002
...

